name: Plugin
version: 1.12
main: me.hilden.plugin.Main
authors: [ HilDen ]
commands:
   spawn:
     description: teleporting on spawn
     usage: /spawn
   kits:
    description: open menu kits
    usage: /kits
   stats:
      description: stats
      usage: /stats

